=== tobiaskalmes/MobileComputingJANE/JANE_Simulation/_output/de/uni_trier/jane/simulation/dynamic/mobility_source/scripted_mobility.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT address (#PCDATA)>

<!ELEMENT end_time (#PCDATA)>

<!ELEMENT mobility (move+)>

<!ELEMENT move (start_time,end_time,new_position)>

<!ELEMENT new_position (x,y)>

<!ELEMENT node (address,sending_radius,position,mobility?)>

<!ELEMENT position (x,y)>

<!ELEMENT scripted_mobility (node+)>

<!ELEMENT sending_radius (#PCDATA)>

<!ELEMENT start_time (#PCDATA)>

<!ELEMENT x (#PCDATA)>

<!ELEMENT y (#PCDATA)>

=== tobiaskalmes/MobileComputingJANE/JANE_Simulation/de/uni_trier/jane/simulation/dynamic/mobility_source/scripted_mobility_example2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scripted_mobility SYSTEM "scripted_mobility.dtd">

<scripted_mobility>

	<node>
		<address>0</address>
		<sending_radius>250</sending_radius>
		<position><x>50</x><y>300</y></position>
		<mobility>
			<move>
				<start_time>1.0</start_time>
				<end_time>1.5</end_time>
				<new_position><x>50</x><y>200</y></new_position>
			</move>
		</mobility>
	</node>

	<node>
		<address>1</address>
		<sending_radius>250</sending_radius>
		<position><x>100</x><y>200</y></position>
		<mobility>
			<move>
				<start_time>1.0</start_time>
				<end_time>1.5</end_time>
				<new_position><x>100</x><y>100</y></new_position>
			</move>
		</mobility>
	</node>

	<node>
		<address>2</address>
		<sending_radius>250</sending_radius>
		<position><x>150</x><y>300</y></position>
		<mobility>
			<move>
				<start_time>1.0</start_time>
				<end_time>1.5</end_time>
				<new_position><x>150</x><y>200</y></new_position>
			</move>
		</mobility>
	</node>

	<node>
		<address>3</address>
		<sending_radius>250</sending_radius>
		<position><x>300</x><y>250</y></position>
	</node>

</scripted_mobility>

=== tobiaskalmes/MobileComputingJANE/JANE_Simulation/de/uni_trier/jane/simulation/dynamic/mobility_source/scripted_mobility_example1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scripted_mobility SYSTEM "scripted_mobility.dtd">

<scripted_mobility>

	<node>
		<address>0</address>
		<sending_radius>50</sending_radius>
		<position><x>10</x><y>10</y></position>
		<mobility>
			<move>
				<start_time>10</start_time>
				<end_time>20</end_time>
				<new_position><x>20</x><y>20</y></new_position>
			</move>
		</mobility>
	</node>

	<node>
		<address>1</address>
		<sending_radius>50</sending_radius>
		<position><x>30</x><y>20</y></position>
		<mobility>
			<move>
				<start_time>11</start_time>
				<end_time>19</end_time>
				<new_position><x>2</x><y>30</y></new_position>
			</move>
		</mobility>
	</node>

	<node>
		<address>2</address>
		<sending_radius>50</sending_radius>
		<position><x>130</x><y>120</y></position>
		<mobility>
			<move>
				<start_time>15</start_time>
				<end_time>25</end_time>
				<new_position><x>20</x><y>90</y></new_position>
			</move>
		</mobility>
	</node>

</scripted_mobility>
