=== tobiaskalmes/MobileComputingJANE/JANE_Simulation/de/uni_trier/jane/simulation/dynamic/mobility_source/fixed_nodes.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT address (#PCDATA)>

<!ELEMENT fixed_nodes (node+)>

<!ELEMENT node (address,position,sending_radius)>

<!ELEMENT position (x,y)>

<!ELEMENT sending_radius (#PCDATA)>

<!ELEMENT x (#PCDATA)>

<!ELEMENT y (#PCDATA)>

=== tobiaskalmes/MobileComputingJANE/JANE_Simulation/_output/de/uni_trier/jane/simulation/dynamic/mobility_source/fixed_nodes_example2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fixed_nodes SYSTEM "fixed_nodes.dtd">

<fixed_nodes>

	<node>
		<address>0</address>
		<position><x>450</x><y>400</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>1</address>
		<position><x>460</x><y>410</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>2</address>
		<position><x>440</x><y>395</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>3</address>
		<position><x>450</x><y>390</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>4</address>
		<position><x>460</x><y>400</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>5</address>
		<position><x>460</x><y>390</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>24</address>
		<position><x>470</x><y>390</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>25</address>
		<position><x>470</x><y>400</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>26</address>
		<position><x>470</x><y>410</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>27</address>
		<position><x>470</x><y>420</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>28</address>
		<position><x>460</x><y>420</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>29</address>
		<position><x>450</x><y>420</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>48</address>
		<position><x>430</x><y>410</y></position>
		<sending_radius>50</sending_radius>
	</node>

	<node>
		<address>6</address>
		<position><x>350</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>7</address>
		<position><x>360</x><y>110</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>8</address>
		<position><x>340</x><y>95</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>9</address>
		<position><x>350</x><y>90</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>10</address>
		<position><x>360</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>11</address>
		<position><x>360</x><y>90</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>30</address>
		<position><x>370</x><y>90</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>31</address>
		<position><x>370</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>32</address>
		<position><x>370</x><y>110</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>33</address>
		<position><x>370</x><y>120</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>34</address>
		<position><x>360</x><y>120</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>35</address>
		<position><x>350</x><y>120</y></position>
		<sending_radius>50</sending_radius>
	</node>

	<node>
		<address>12</address>
		<position><x>50</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>13</address>
		<position><x>60</x><y>110</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>14</address>
		<position><x>40</x><y>95</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>15</address>
		<position><x>50</x><y>90</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>16</address>
		<position><x>60</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>17</address>
		<position><x>60</x><y>90</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>36</address>
		<position><x>70</x><y>90</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>37</address>
		<position><x>70</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>38</address>
		<position><x>70</x><y>110</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>39</address>
		<position><x>70</x><y>120</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>40</address>
		<position><x>60</x><y>120</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>41</address>
		<position><x>50</x><y>120</y></position>
		<sending_radius>50</sending_radius>
	</node>

	<node>
		<address>18</address>
		<position><x>150</x><y>300</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>19</address>
		<position><x>160</x><y>310</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>20</address>
		<position><x>140</x><y>295</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>21</address>
		<position><x>150</x><y>290</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>22</address>
		<position><x>160</x><y>300</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>23</address>
		<position><x>160</x><y>290</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>42</address>
		<position><x>170</x><y>290</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>43</address>
		<position><x>170</x><y>300</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>44</address>
		<position><x>170</x><y>310</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>45</address>
		<position><x>170</x><y>320</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>46</address>
		<position><x>160</x><y>320</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>47</address>
		<position><x>150</x><y>320</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>49</address>
		<position><x>180</x><y>290</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>50</address>
		<position><x>180</x><y>300</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>51</address>
		<position><x>180</x><y>310</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>52</address>
		<position><x>180</x><y>320</y></position>
		<sending_radius>50</sending_radius>
	</node>

	<node>
		<address>100</address>
		<position><x>440</x><y>360</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>101</address>
		<position><x>420</x><y>330</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>102</address>
		<position><x>400</x><y>300</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>103</address>
		<position><x>370</x><y>320</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>104</address>
		<position><x>400</x><y>280</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>105</address>
		<position><x>410</x><y>260</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>106</address>
		<position><x>420</x><y>240</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>107</address>
		<position><x>400</x><y>200</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>108</address>
		<position><x>390</x><y>190</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>109</address>
		<position><x>380</x><y>170</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>110</address>
		<position><x>340</x><y>160</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>111</address>
		<position><x>350</x><y>140</y></position>
		<sending_radius>50</sending_radius>
	</node>

	<node>
		<address>112</address>
		<position><x>320</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>113</address>
		<position><x>300</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>114</address>
		<position><x>290</x><y>110</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>115</address>
		<position><x>260</x><y>120</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>116</address>
		<position><x>250</x><y>110</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>117</address>
		<position><x>210</x><y>110</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>118</address>
		<position><x>170</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>119</address>
		<position><x>140</x><y>95</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>120</address>
		<position><x>120</x><y>110</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>121</address>
		<position><x>90</x><y>100</y></position>
		<sending_radius>50</sending_radius>
	</node>

	<node>
		<address>122</address>
		<position><x>90</x><y>150</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>123</address>
		<position><x>120</x><y>180</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>124</address>
		<position><x>140</x><y>200</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>125</address>
		<position><x>130</x><y>230</y></position>
		<sending_radius>50</sending_radius>
	</node>
	<node>
		<address>126</address>
		<position><x>145</x><y>250</y></position>
		<sending_radius>50</sending_radius>
	</node>

</fixed_nodes>
